trigger:
  branches:
    include:
      - main

jobs:
  - job: DeployStorageAccount
    displayName: 'Deploy Azure Storage Account'
    pool:
      name: smahapool

    steps:
      - checkout: self

      - task: PowerShell@2
        displayName: 'Deploy Storage Account'
        inputs:
          targetType: 'inline'
          script: |
            $clientId = "442398b9-681a-4843-821f-95ac554535da"
            $clientSecret = "dxE8Q~DiM~mZmylAU~MGBcxjq.5Q_XWXIEtEOdwx"
            $tenant = "0e6efad9-caef-45e7-9a2f-cc14d82ece6b"
            # Authenticate and create the service connection
            az login --service-principal -u $clientId -p $clientSecret --tenant $tenantId
            echo "smaha im done"
      
