trigger:
  branches:
    include:
      - main

jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template'
    pool: smahapool

    steps:
      - checkout: self

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy ARM Template'
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 1
          subscriptionId: 13e19292-1bdf-455b-bb42-ff0b0473dc2c
          resourceGroupName: smaha-hw
          templateLocation: https://github.com/SmahaElsana/smahahw/blob/master/azuredeploy.json
          csmFileURL: https://github.com/SmahaElsana/smahahw/blob/master/azuredeploy.json
          csmParametersFileURL: https://github.com/SmahaElsana/smahahw/blob/master/azuredeploy.parameters.json
