trigger:
  branches:
    include:
      - main

jobs:
  - job: DeployStorageAccount
    displayName: 'Deploy Azure Storage Account'
    pool:
      name: smahapool

    steps:
      - checkout: self

      - task: PowerShell@2
        displayName: 'Deploy Storage Account'
        inputs:
          targetType: 'inline'
          script: |
            # Authenticate with Azure using email and password
            Connect-AzAccount 
            # Create resource group
            $resourceGroupName = 'smahagrp'
            $location = eastus
            New-AzResourceGroup -Name $resourceGroupName -Location $location -Force

            # Create storage account
            $storageAccountName = 'fmlsmaha'
            $sku = 'Standard_LRS'
            $storageAccount = New-AzResourceGroupDeployment -ResourceGroupName $resourceGroupName -Name $storageAccountName -SkuName $sku -Location $location

            Write-Output "Storage account created: $($storageAccount.Name)"

            # Add any additional steps or configurations as needed
