trigger:
  branches:
    include:
      - main

jobs:
  - job: Build
    displayName: 'Build Job'
    pool:
      name: smahapool
    
    steps:
      - script: echo "Running build process on self-hosted agent"
        displayName: 'Build Step'