# trigger:
#   branches:
#     include:
#       - main  # Replace with the branch you want to trigger the pipeline on

# pool:
#   name: smahapool

# steps:
# - task: RdpOverSsh@1
#   inputs:
#     azureSubscriptionEndpoint: 'smahacon'  # Replace with the name of your Azure subscription endpoint
#     virtualMachineName: 'myWinVm'  # Replace with the name of your Azure VM
#     username: 'smahaAdmin'  # Replace with the username for the RDP connection
#     privateKey: '$(PrivateKeyVariable)'  # Replace with the name of the secret variable that holds the private key
#     sshEndpoint: 'mySSHEndpoint'  # Replace with the name of your SSH endpoint configured in Azure DevOps

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'smahacon'  # Replace with the name of your Azure subscription
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       # Enter your commands to run on the Azure VM
#       echo "Hello, Azure VM!"

trigger:
  branches:
    include:
      - main  # Replace with the branch you want to trigger the pipeline on

jobs:
- job: RunPythonScript
  displayName: 'Run Python Script'
  pool:
    name: smahapool  # Replace with the name of your self-hosted agent pool

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Replace with the desired Python version
      addToPath: true

  # - script: |
  #     python -m pip install --upgrade pip
  #     pip install -r requirements.txt  # Replace with the path to your requirements.txt file
  #   displayName: 'Install dependencies'

  - script: |
      python task5.py  # Replace with the path to your Python file
    displayName: 'Run Python script'
