trigger:
  branches:
    include:
      - main  # Replace with the branch you want to trigger the pipeline on

pool:
  name: smahapool

steps:
- task: WinRm@2
  inputs:
    connectionType: 'WinRM'
    targets: 'myWinVm'  # Replace with the hostname or IP address of your Windows Server 2012 VM
    port: '5985'  # Replace with the WinRM port number if different from the default (5985)
    proto: 'http'  # Replace with 'https' if using WinRM over HTTPS
    username: 'smahaAdmin'  # Replace with the username for connecting to the Windows Server 2012 VM
    password: 'smahaAdmin123'  # Replace with the secure password variable or provide the password directly
