trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    displayName: 'Azure Login'
    inputs:
      azureSubscription: 'smahacon'
      scriptLocation: 'inlineScript'
      inlineScript: 'az login'

  - task: AzureCLI@2
    displayName: 'Create Blob Container'
    inputs:
      azureSubscription: 'smahacon'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az storage container create --name container12 --account-name smahastorage1111 --account-key amgY8vqarqsLxK8o27Jbu7CIptQpuKW3y0GEu/vQk8ptJn+fI3acxoEqmIiSZ0ljmbnnPmBrVACd+AStRpArxQ==

  - task: AzureCLI@2
    displayName: 'Upload Blob'
    inputs:
      azureSubscription: 'smahacon'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az storage blob upload --container-name container12 --name myblob --type block --account-name smahastorage1111 --account-key amgY8vqarqsLxK8o27Jbu7CIptQpuKW3y0GEu/vQk8ptJn+fI3acxoEqmIiSZ0ljmbnnPmBrVACd+AStRpArxQ== --content-type "text/plain" --content-encoding "utf-8" --content "hello there my friend"
