trigger:
  branches:
    include:
      - main  # Replace with the branch you want to trigger the pipeline on

pool:
  name: smahapool

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'smahacon'  # Replace with the name of your Azure subscription
    ScriptType: 'InlineScript'
    azurePowerShellVersion: '3.0.0'  # Replace with the desired Azure PowerShell version
    Inline: |
      $rgName = 'smaha-hw'  # Replace with the name of your resource group
      $vmName = 'myWinVm'  # Replace with the name of your VM

      # Connect to Azure VM using WinRM
      $username = 'smahaAdmin'  # Replace with the username for connecting to the Windows Server 2012 VM
      $password = ConvertTo-SecureString 'smahaAdmin123' -AsPlainText -Force  # Replace 'yourpassword' with the actual password
      $cred = New-Object System.Management.Automation.PSCredential($username, $password)
      $session = New-PSSession -ComputerName $vmName -Credential $cred

      # Run commands on the VM
      Invoke-Command -Session $session -ScriptBlock {
          # Enter your commands to run on the Windows Server 2012 VM
      }

      # Disconnect from the Azure VM
      Remove-PSSession -Session $session
