trigger:
  branches:
    include:
      - main  # Replace with the branch you want to trigger the pipeline on

pool:
  name: smahapool

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'smahacon'  # Replace with the name of your Azure subscription
    ScriptType: 'InlineScript'
    Inline: |
      $rgName = 'smaha-hw'  # Replace with the name of your resource group
      $vmName = 'myWinVm'  # Replace with the name of your VM

      # Connect to Azure VM
      $cred = Get-Credential -UserName 'smahaAdmin' -Message 'Enter the username and password to connect to the VM'
      $session = New-PSSession -ComputerName $vmName -Credential $cred

      # Disconnect from Azure VM
      Remove-PSSession -Session $session