trigger:
  branches:
    include:
      - main

jobs:
- job: ConnectToVM
  displayName: Connect to Azure VM
  pool:
    name: smahapool

  steps:
  - task: WinRmToolkit@0
    inputs:
      connectionType: 'WinRMOverHttp'
      targetMachine: 'myWinVm'
      username: 'smahaAdmin'
      password: 'smahaAdmin123'
      scriptType: 'Inline'
      inlineScript: |
        echo "connected succesfully"
        # Run your commands on the remote VM
        
        # For example, execute a PowerShell script
        Invoke-Command -ScriptBlock {
          Get-Process
        }
